spring:
  datasource:
    #   数据源基本配置
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/youngpioneer?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
#整合mybatis
mybatis:
  type-aliases-package: com.example.youngpioneer.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
